### ISSUE TITLE
Extension does not detect Pod container missing "image" property

### ISSUE THREAD

**Issue by pcgeek86** [vscode-kubernetes-tools/vscode-kubernetes-tools#1085]
### Summary
The VSCode Kubernetes extension does not detect when the `image` property is missing in a Kubernetes Pod YAML manfiest.

### Repro Steps

Save this to a file. No problems are detected.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
```
