### ISSUE TITLE
Consider better helm snippets support?

### ISSUE THREAD

**Issue by longkai** [vscode-kubernetes-tools/vscode-kubernetes-tools#1109]
Hello, I notice the default helm template snippets is not helpful and sometimes cause confusion especially for new comers.

For example, when we use `if` snippets in the template it will complete like this:

```yaml
containers:
- name: {{ .Chart.Name }}
  {{- if condition -}}
  imagePullPolicy: Always # template we would insert
  {{- end -}}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
```

However, the right side `-` is no needed for yaml, it will cause helm fail to render since it broke the yaml syntax. Which cause the following error:

```
Error: YAML parse error on starter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 40: mapping values are not allowed in this context

Use --debug flag to render out invalid YAML
```

Most of the time, the templates we write will always delete the right side `-` like `with` `if` and `range` and so on.

So I find the `rawsnippets/` does not consistent(the left and right side `-`) and not helpful each time we use.

I would like to makes a contribute if you think is rational.
