### ISSUE TITLE
Error loading kubeconfig file yaml: line 7: could not find expected ':'

### ISSUE THREAD

**Issue by Toni744** [vscode-kubernetes-tools/vscode-kubernetes-tools#1200]
Getting this error trying to access kubernetes resources using kubectl

error: error loading config file "/home/eksadmin/.kube/config" : yaml: line 7: could not find expected ':'
here's my kubectl token in the config file

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://A86E68FF2DA87AEBC8A36BC58EFFF12E.gr7.us-east-2.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3hNakUyTkRVeU4xb1hEVE16TURjd09URTJORFV5TjFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaW
FJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3hsCmNvUm5JMnRDV05heDA0ZTVZWDgyeWtHUTVlanpLK25CUEJJcDd3WEoxYUVtRjE2aG0vYVd1eFJ5RjBLNzNsajUKMEp2Y2xwYytNdWdYenNpTndWZk5qQ1dYY0xRNlNxczdQV09nSU5sdWhqemVRZUVycFI1U3pRdnNsemo3c2ZhZAo1YkFUaytISEVkWWVvd2
wrWDZUYmpoWmlyc0tONkdIbFBVeXNBa05BcEREQmNORlNuOU5Ic1FkUlYzd0JjcUhTCi8zVXJER0pjOTl0NU4zV3NuaTBzMUVqajJpQ2tMZ0s4bldMZHM0d0xOTkVVY3JSWWZPZjlJb1lzTUpHeDRYSWwKWGdwWEtaSDhBb2h5UUFuNDI2M0FhUlhWY1pBQWR0WjlvNE5ESEhadk1ldUFPRStNdDM4bTJiYjFXSWdPRldQQQpOZ3RnNnpIdGxDWC9HaUhqcGNzQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNOTZjbFJVeWNnektVRXY3NG9xZ0JLMHpOZEZNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR1NUa3lSWVlmNVFTL3hsS3VCQwpuOGxWd3JJN2RYK3hCTFVU
eGljRjRmMGh6eEk1N094UWlrR3N2OHpZR1pCVW9PNXhuSy8wQUtPQTRpWk1neEZjCnc4TzBpay91b3ZUMEU4ZFN3OTRVajZUWmFzZjFlNlJTOUFYMUVUV0tGV2VOMkNIcUxZK2VvNkdSYlpUeXMwK00KY3JyTE1xQ2dZQ1NmUmZpTFRNa3NiY2xXSVZTdHB0M0JZZ3N5dHowNFp0NHRpaG56ZzlCY0hDc3Q1bk9oaXVWcApLVkZ1YmtxZHFITXV1eTlBZ
UdaYlBVVlE5NS84NHhzaDhhWWFGK3licDZPa0dLN3FPMUgrMkpnYkFBYUtVVmRqCnZXZENJa01sWFlUZmFpcHE4RS9jWGhzMmRhcnBKeTFXeHMzMFY5OEdmS0E2YkcvdWhGZkpTdjQ0MDgyaENqL3kKNkJZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "eks-ACADA"
```
