### ISSUE TITLE
Support recommended metadata labels in snippets

### ISSUE THREAD

**Issue by igorakkerman** [vscode-kubernetes-tools/vscode-kubernetes-tools#1479]
Hi, it is recommended to use specific common metadata labels for resources, prefixed with `app.kubernetes.io/`, e.g.
```yaml
metadata: 
  labels: 
    app.kubernetes.io/name: my-app
```
A list is given here:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

In the snippets, we currently have:
```yaml
  metadata:
    name: ${1:myapp}
    labels:
      name: ${1:myapp}
```
Could the recommended `app.kubernetes.io/`-prefixed labels be used in the snippets?
