### ISSUE TITLE
ReplicaSet snippet

### ISSUE THREAD

**Issue by nwipfli** [vscode-kubernetes-tools/vscode-kubernetes-tools#669]
Hi,

Is it possible to add a snippet for the ReplicaSet ?

Thanks
Nicolas

**Comment by itowlson** [comment]
Sorry for the slow reply - I've been on holiday.  Yes, we can add a snippet - would you be able to suggest text?  (If not I can look it out from the documentation.)

**Comment by nwipfli** [comment]
Do you have an example from another existing snippet so that I make sure to understand exactly what is needed ?

**Comment by emangual** [comment]
@itowlson  Just starting to get into kubernetes myself. Here is a sample that might help. 

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
```
Reference: [Kubernetes Replicaset](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/#example)
